

POWERFUL_QUOTES = [
    "🌟 **Believe in yourself!**\nYou are braver than you think, more talented than you know, and capable of more than you imagine.",
    "🔥 **Push your limits!**\nGreat things never come from comfort zones. Keep pushing forward!",
    "💪 **Stay Strong!**\nDifficult roads often lead to beautiful destinations. Don't give up!",
    "🚀 **Take Action!**\nThe secret of getting ahead is getting started. Make today count.",
    "💎 **You are valuable!**\nYour potential is endless. Trust the process and keep grinding.",
    "🌅 **New Day, New Strength!**\nEvery morning is a blank canvas. Paint it with positivity and purpose.",
    "🦅 **Rise Above!**\nDon't let the noise of others' opinions drown out your own inner voice.",
    "📈 **Daily Progress!**\nSuccess is the sum of small efforts, repeated day in and day out.",
    "🧱 **Build Your Legacy!**\nDon't wait for opportunity. Create it with your own hands.",
    "⏳ **Time is Wealth!**\nStop wasting time on things that don't help you grow. Focus on your goals.",
    "🧠 **Mindset Matters!**\nWhether you think you can or you think you can't, you are right.",
    "⛰️ **Conquer Yourself!**\nIt is not the mountain we conquer, but ourselves.",
    "🎯 **Stay Focused!**\nDon't look at the distractions; look at the destination.",
    "⚡ **Energy Flows!**\nWhere focus goes, energy flows. Direct yours toward greatness.",
    "🌊 **Be Relentless!**\nBe like water—persistent enough to wear down even the hardest rock.",
    "🛠️ **Hard Work Wins!**\nSkill is developed by hours and hours of beating on your craft.",
    "🌓 **Overcome Shadows!**\nEven the darkest night will end and the sun will rise. Keep going.",
    "🛡️ **Unstoppable!**\nYour current situation is not your final destination. The best is yet to come.",
    "🌋 **Inner Fire!**\nA heart on fire for a dream can melt any obstacle in its path.",
    "⛓️ **Break Free!**\nYou are only confined by the walls you build yourself. Break them down.",
    "🦁 **Lion Mentality!**\nA lion doesn't lose sleep over the opinion of sheep. Lead your life.",
    "🌪️ **Stay Grounded!**\nYou cannot calm the storm, but you can calm yourself. The storm will pass.",
    "🏹 **Aim Higher!**\nIf you want to live a happy life, tie it to a goal, not to people or things.",
    "🥊 **Keep Fighting!**\nIt’s not about how hard you hit. It’s about how hard you can get hit and keep moving forward.",
    "🕯️ **Be the Light!**\nBetter to light a candle than to curse the darkness. Be the change.",
    "🌱 **Growth Hurts!**\nChange is hard at first, messy in the middle, and gorgeous at the end.",
    "💎 **Pressure Makes Diamonds!**\nDon't fear the pressure. It is preparing you for a brilliant future.",
    "👑 **Own Your Day!**\nDon't count the days, make the days count.",
    "🏆 **Winning Habits!**\nSuccess isn't always about greatness. It's about consistency.",
    "🌍 **Change the World!**\nThe people who are crazy enough to think they can change the world are the ones who do.",
    "💡 **Visionary Mind!**\nThe only thing worse than being blind is having sight but no vision.",
    "🌠 **Dream Big!**\nShoot for the moon. Even if you miss, you'll land among the stars.",
    "🔑 **The Key to Success!**\nWake up with determination. Go to bed with satisfaction.",
    "🚶 **The First Step!**\nA journey of a thousand miles begins with a single step. Take it now.",
    "🎭 **Be Authentic!**\nBe yourself; everyone else is already taken.",
    "🌻 **Stay Positive!**\nKeep your face always toward the sunshine—and shadows will fall behind you.",
    "🏁 **Finish Strong!**\nIt doesn't matter how you start. It matters how you finish.",
    "⚖️ **Find Balance!**\nYou cannot pour from an empty cup. Take care of yourself first.",
    "🤐 **Silence is Power!**\nWork hard in silence, let your success be your noise.",
    "🙏 **Gratitude!**\nGratitude turns what we have into enough. Be thankful for today.",
    "🧘 **Peace of Mind!**\nNothing can bring you peace but yourself.",
    "📖 **Keep Learning!**\nLive as if you were to die tomorrow. Learn as if you were to live forever.",
    "🍎 **Health is Wealth!**\nA healthy outside starts from the inside. Respect your body.",
    "🤝 **Kindness!**\nKindness is a language which the deaf can hear and the blind can see.",
    "🕰️ **Now or Never!**\nYesterday is history, tomorrow is a mystery, today is a gift of God.",
    "🌈 **Hope!**\nEvery cloud has a silver lining. Look for the rainbow after the rain.",
    "🐘 **Patience!**\nPatience is not the ability to wait, but the ability to keep a good attitude while waiting.",
    "🔥 **Stay Hungry!**",
    "🚀 **Sky is Not the Limit!**",
    "💎 **Rare and Valuable!**",
    "🦁 **Be a Warrior, Not a Worrier!**",
    "🎯 **Focus!**",
    "⚡ **Do It Now!**",
    "🏆 **Champion Mindset!**",
    "💪 **Stronger Every Day!**",
    "🌟 **Shine Bright!**",
    "🌍 **Make an Impact!**",
    "🧗 **The Climb!**\nThe view from the top is worth every drop of sweat it took to get there.",
    "🔋 **Recharge!**\nRest if you must, but never quit.",
    "🛸 **Think Outside!**\nYou can't solve problems with the same thinking that created them.",
    "🍂 **Let Go!**\nBe like a tree and let the dead leaves drop. Start fresh.",
    "⛲ **Unlimited Potential!**\nYou are the only person who can limit your greatness.",
    "🌌 **Infinite Possibilities!**\nDon't settle for 'good enough' when 'extraordinary' is within reach.",
    "🧩 **The Missing Piece!**\nYou are the architect of your own happiness.",
    "🧭 **Find Your Way!**\nDon't follow where the path may lead. Go where there is no path and leave a trail.",
    "🦅 **Fly High!**\nAn eagle earns its wings in the wind, not in the nest.",
    "⚓ **Be the Anchor!**\nBe steady in your purpose, even when the world is chaotic.",
    "💸 **Invest in Yourself!**\nThe best investment you can make is in your own mind and skills.",
    "📈 **Compounding Effort!**\nSmall habits lead to massive results over time. Keep stacking wins.",
    "🔨 **Forge Your Path!**\nLife isn't about finding yourself. Life is about creating yourself.",
    "🏎️ **No Speed Limit!**\nYour only limit is your soul. Speed up your progress.",
    "🦾 **Resilience!**\nFall seven times, stand up eight.",
    "🔥 **Ignite!**\nDon't wait for a spark. Be the fire.",
    "🐉 **Unleash the Dragon!**\nThere is a power inside you waiting to be awakened.",
    "🌪️ **Be the Storm!**\nWhen they say you can't survive the storm, whisper: 'I am the storm.'",
    "🏔️ **Peak Performance!**\nExcellence is not an act, but a habit.",
    "🏛️ **Build Stability!**\nFoundation first, empire second. Build your roots deep.",
    "🎈 **Lift Others!**\nWe rise by lifting others.",
    "✨ **Sparkle!**\nNever let anyone dull your sparkle.",
    "🍀 **Luck is Earned!**\nLuck is what happens when preparation meets opportunity.",
    "🎻 **Harmony!**\nLive your life in harmony with your values.",
    "🎨 **Masterpiece!**\nYour life is your message to the world. Make it a masterpiece.",
    "🐚 **Listen Inward!**\nThe answers you seek are already inside you. Listen closely.",
    "🛤️ **Track Your Success!**\nWhat gets measured, gets managed. Keep track of your wins.",
    "🚪 **Open Doors!**\nIf the door doesn't open, it's not your door. Move to the next one.",
    "🕯️ **Inner Glow!**\nNo beauty shines brighter than that of a good heart.",
    "🗺️ **Explore!**\nNot all those who wander are lost. Find your adventure.",
    "💯 **Give Your All!**\nDo your best until you know better. Then when you know better, do better.",
    "🌊 **Flow State!**\nLet go of the struggle and find your rhythm.",
    "🌋 **Erupt with Passion!**\nPassion is energy. Feel the power that comes from focusing on what excites you.",
    "🛡️ **Defend Your Dreams!**\nDon't let anyone steal your vision.",
    "⚡ **Shock the World!**\nThey will doubt you until you prove them wrong. Do it anyway.",
    "🏗️ **Under Construction!**\nBe patient with yourself. You are building a masterpiece.",
    "🧬 **DNA of a Winner!**\nYou were born to win, but to be a winner, you must plan to win.",
    "⏳ **Legacy!**\nWhat you do today is what you will be remembered for tomorrow.",
    "🔋 **Endless Drive!**\nSuccess is not final, failure is not fatal: it is the courage to continue that counts.",
    "🌟 **You are the Star!**\nStop looking for a hero. Look in the mirror."
]
